### ISSUE TITLE
Streamline suggestions

### ISSUE THREAD

**Issue by scith** [Snipees/couchpotato_ynh#1]
Hello, I would be very interested in contributing to this package with you (e.g., adding links with Transmission)
However, my concern with this package is the "local/remote" install choices in the manifest. I don't think this needs to be managed by this package. It complexifies greatly the install process, and it can already be done by the [redirect_ynh app](https://github.com/YunoHost-Apps/redirect_ynh)

I would therefore like to remove from the manifest and install process at least:
- method
- port
- host

Even better, also remove:
- public: because the app needs to be private for SSO. Otherwise the user has to enter a username, as there is no LDAP integration. However, this would also remove access from mobile apps unfortunately, as there is no passwordless API I think.
- data: is this even used in the install script? I can't find it in the script
- fork: complex for a beginner user. Which fork to use? I think we should make this choice in the packaging. People who don't agree can fork the app to change the sources.

As a result, this would leave the package only with domain and path...

What do you think?

**Comment by Snipees** [comment]
Hello,

At the time, I wrote these scripts as an exercise to test the possibilities offered by YNH.
Today, I no longer use YNH because the project did not correspond to my needs. But I think it's a wonderful tool, so I always encourage it.

I agree with your point of view. This installation script is unnecessarily complicated and could be simplified without causing inconvenience.
Especially since the Redirect app is a great alternative.

The choice of the installation method and the source repository can be easily removed.

Concerning the "data" argument, it is not used in the install script but in the remove script, as mentioned in the manifest. (`keep_data=$1`)

**Comment by scith** [comment]
Oh OK I see. Thanks for the insight :)
Do you mind if I continue the development of your package then?
May I also ask why YunoHost is not corresponding to your needs anymore?
Thanks

**Comment by rigelk** [comment]
Having used extensively the [redirect_ynh app](https://github.com/YunoHost-Apps/redirect_ynh), I can tell it doesn’t provide everything an integrated choice can: some applications require modified nginx configurations (ex: Ajenti for "Keep-Alive" headers, Netdata for upgrade method (websockets)).

I agree a decoupling would be nice. But considered the redirection is a one-time work and arguably little hassle during the installation, I would keep the integarted remote configuration.

My point is, _until some official way of decoupling remote/local configurations emerges_ in the YunoHost community, we should either:

* keep track of changes (if any) necessary to make the Redirect app to work (in a wiki page of the readme)

OR

* integrate the remote configuration process as is already the case here

**Comment by scith** [comment]
I see your point with redirect_ynh, but I think that remote apps are better suited to redirect_ynh for the following reasons:
- A YunoHost app is supposed to install an app on the server and link it to YunoHost SSO. This is best achieved when the app is installed locally
- YunoHost apps are supposed to be easily installable. I find this remote install to be too complex. An alternative as you suggest would be to have this in core (perhaps you could open a ticket for this on dev.yunohost.org)?
- Is the use of remotely installed apps frequent? I am a frequent user of redirect_ynh myself (otherwise I wouldn't have packaged it in the first place...), but honestly I don't think it is such a common scenario. Especially as it requires extra skills to deploy apps elsewhere without YunoHost, and sometimes even extra servers.

However I really like your idea of having a databases of configs for redirect_ynh. Perhaps this could even be included in install (such as asking if the user wants to redirect to a specific app). I have opened a topic on the forum last month for such purpose, with no answer yet :( https://forum.yunohost.org/t/redirect-ynh-share-your-case-examples-and-config/2182
One case study has been posted here: https://forum.yunohost.org/t/proxy-nginx-websocket/2169/2

**Comment by scith** [comment]
See https://github.com/YunoHost-Apps/couchpotato_ynh/pull/2 to test
