### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by maniackcrudelis** [Snipees/couchpotato_ynh#4]
Hi,

your app failed to install on the current version of YunoHost
https://ci-apps.yunohost.org/jenkins/job/couchpotato%20(Community)/4/console

On 24 of march, your app will be decreased at notworking status.

**Comment by frju365** [comment]
The app works now.

**Comment by maniackcrudelis** [comment]
Ok good.
Just let's a while for the app will be checked by the CI.
And we'll can close this issue.
