### ISSUE TITLE
Couchpotato white page error when installed at root of a subdomain

### ISSUE THREAD

**Issue by mokas01** [Snipees/couchpotato_ynh#9]
Hi,

I tried to install couchpotato on the root of a subfolder. It worked, but I only had a white page instead of the home page. I had to go and change the settings (/home/yunohost.app/couchpotato/settings.conf and change

> url_base = /

into 

> url_base =

Now it works. But you might want to change that in your install script ? Sorry for opening a solved issue, i just wanted to let you know

**Comment by anmol26s** [comment]
Same problem for me

**Comment by yalh76** [comment]
shouold be ok now
